/*
 * Swagger Memverse
 * Memverse API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.memverse.apiclient.model;

import com.google.gson.annotations.SerializedName;

import java.util.Objects;

import io.swagger.annotations.ApiModelProperty;

/**
 * FinalVerse
 */
public class FinalVerse {
    @SerializedName("book")
    private String book = null;

    @SerializedName("chapter")
    private Long chapter = null;

    @SerializedName("last_verse")
    private Long lastVerse = null;

    public FinalVerse book(String book) {
        this.book = book;
        return this;
    }

    /**
     * Get book
     *
     * @return book
     **/
    @ApiModelProperty(value = "")
    public String getBook() {
        return book;
    }

    public void setBook(String book) {
        this.book = book;
    }

    public FinalVerse chapter(Long chapter) {
        this.chapter = chapter;
        return this;
    }

    /**
     * Get chapter
     *
     * @return chapter
     **/
    @ApiModelProperty(value = "")
    public Long getChapter() {
        return chapter;
    }

    public void setChapter(Long chapter) {
        this.chapter = chapter;
    }

    public FinalVerse lastVerse(Long lastVerse) {
        this.lastVerse = lastVerse;
        return this;
    }

    /**
     * Get lastVerse
     *
     * @return lastVerse
     **/
    @ApiModelProperty(value = "")
    public Long getLastVerse() {
        return lastVerse;
    }

    public void setLastVerse(Long lastVerse) {
        this.lastVerse = lastVerse;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        FinalVerse finalVerse = (FinalVerse) o;
        return Objects.equals(this.book, finalVerse.book) &&
                Objects.equals(this.chapter, finalVerse.chapter) &&
                Objects.equals(this.lastVerse, finalVerse.lastVerse);
    }

    @Override
    public int hashCode() {
        return Objects.hash(book, chapter, lastVerse);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class FinalVerse {\n");

        sb.append("    book: ").append(toIndentedString(book)).append("\n");
        sb.append("    chapter: ").append(toIndentedString(chapter)).append("\n");
        sb.append("    lastVerse: ").append(toIndentedString(lastVerse)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

