/*
 * Swagger Memverse
 * Memverse API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.memverse.apiclient.model;

import com.google.gson.annotations.SerializedName;

import org.threeten.bp.LocalDate;

import java.util.Objects;

import io.swagger.annotations.ApiModelProperty;

/**
 * UserInput
 */
public class UserInput {
    @SerializedName("id")
    private Long id = null;

    @SerializedName("login")
    private String login = null;

    @SerializedName("identity_url")
    private String identityUrl = null;

    @SerializedName("name")
    private String name = null;

    @SerializedName("email")
    private String email = null;

    @SerializedName("remember_token_expires_at")
    private String rememberTokenExpiresAt = null;

    @SerializedName("deleted_at")
    private String deletedAt = null;

    @SerializedName("created_at")
    private String createdAt = null;

    @SerializedName("updated_at")
    private String updatedAt = null;

    @SerializedName("last_reminder")
    private LocalDate lastReminder = null;

    @SerializedName("reminder_freq")
    private String reminderFreq = null;

    @SerializedName("newsletters")
    private Boolean newsletters = null;

    @SerializedName("church_id")
    private Long churchId = null;

    @SerializedName("country_id")
    private Long countryId = null;

    @SerializedName("language")
    private String language = null;

    @SerializedName("time_allocation")
    private Long timeAllocation = null;

    @SerializedName("memorized")
    private Long memorized = null;

    @SerializedName("learning")
    private Long learning = null;

    @SerializedName("last_activity_date")
    private LocalDate lastActivityDate = null;

    @SerializedName("show_echo")
    private Boolean showEcho = null;

    @SerializedName("max_interval")
    private Long maxInterval = null;

    @SerializedName("mnemonic_use")
    private LocalDate mnemonicUse = null;

    @SerializedName("american_state_id")
    private Long americanStateId = null;

    @SerializedName("accuracy")
    private Long accuracy = null;

    @SerializedName("all_refs")
    private Boolean allRefs = null;

    @SerializedName("rank")
    private Long rank = null;

    @SerializedName("ref_grade")
    private Long refGrade = null;

    @SerializedName("gender")
    private String gender = null;

    @SerializedName("translation")
    private String translation = null;

    @SerializedName("level")
    private Long level = null;

    @SerializedName("referred_by")
    private Long referredBy = null;

    @SerializedName("show_email")
    private Boolean showEmail = null;

    @SerializedName("auto_work_load")
    private Boolean autoWorkLoad = null;

    @SerializedName("admin")
    private Boolean admin = null;

    @SerializedName("group_id")
    private Long groupId = null;

    @SerializedName("provider")
    private String provider = null;

    @SerializedName("uid")
    private String uid = null;

    @SerializedName("sync_subsections")
    private Boolean syncSubsections = null;

    @SerializedName("quiz_alert")
    private Boolean quizAlert = null;

    @SerializedName("device_token")
    private String deviceToken = null;

    @SerializedName("device_type")
    private String deviceType = null;

    public UserInput id(Long id) {
        this.id = id;
        return this;
    }

    /**
     * Get id
     *
     * @return id
     **/
    @ApiModelProperty(required = true, value = "")
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public UserInput login(String login) {
        this.login = login;
        return this;
    }

    /**
     * Get login
     *
     * @return login
     **/
    @ApiModelProperty(required = true, value = "")
    public String getLogin() {
        return login;
    }

    public void setLogin(String login) {
        this.login = login;
    }

    public UserInput identityUrl(String identityUrl) {
        this.identityUrl = identityUrl;
        return this;
    }

    /**
     * Get identityUrl
     *
     * @return identityUrl
     **/
    @ApiModelProperty(value = "")
    public String getIdentityUrl() {
        return identityUrl;
    }

    public void setIdentityUrl(String identityUrl) {
        this.identityUrl = identityUrl;
    }

    public UserInput name(String name) {
        this.name = name;
        return this;
    }

    /**
     * Get name
     *
     * @return name
     **/
    @ApiModelProperty(value = "")
    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public UserInput email(String email) {
        this.email = email;
        return this;
    }

    /**
     * Get email
     *
     * @return email
     **/
    @ApiModelProperty(required = true, value = "")
    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public UserInput rememberTokenExpiresAt(String rememberTokenExpiresAt) {
        this.rememberTokenExpiresAt = rememberTokenExpiresAt;
        return this;
    }

    /**
     * Get rememberTokenExpiresAt
     *
     * @return rememberTokenExpiresAt
     **/
    @ApiModelProperty(value = "")
    public String getRememberTokenExpiresAt() {
        return rememberTokenExpiresAt;
    }

    public void setRememberTokenExpiresAt(String rememberTokenExpiresAt) {
        this.rememberTokenExpiresAt = rememberTokenExpiresAt;
    }

    public UserInput deletedAt(String deletedAt) {
        this.deletedAt = deletedAt;
        return this;
    }

    /**
     * Get deletedAt
     *
     * @return deletedAt
     **/
    @ApiModelProperty(value = "")
    public String getDeletedAt() {
        return deletedAt;
    }

    public void setDeletedAt(String deletedAt) {
        this.deletedAt = deletedAt;
    }

    public UserInput createdAt(String createdAt) {
        this.createdAt = createdAt;
        return this;
    }

    /**
     * Get createdAt
     *
     * @return createdAt
     **/
    @ApiModelProperty(value = "")
    public String getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(String createdAt) {
        this.createdAt = createdAt;
    }

    public UserInput updatedAt(String updatedAt) {
        this.updatedAt = updatedAt;
        return this;
    }

    /**
     * Get updatedAt
     *
     * @return updatedAt
     **/
    @ApiModelProperty(value = "")
    public String getUpdatedAt() {
        return updatedAt;
    }

    public void setUpdatedAt(String updatedAt) {
        this.updatedAt = updatedAt;
    }

    public UserInput lastReminder(LocalDate lastReminder) {
        this.lastReminder = lastReminder;
        return this;
    }

    /**
     * Get lastReminder
     *
     * @return lastReminder
     **/
    @ApiModelProperty(value = "")
    public LocalDate getLastReminder() {
        return lastReminder;
    }

    public void setLastReminder(LocalDate lastReminder) {
        this.lastReminder = lastReminder;
    }

    public UserInput reminderFreq(String reminderFreq) {
        this.reminderFreq = reminderFreq;
        return this;
    }

    /**
     * Get reminderFreq
     *
     * @return reminderFreq
     **/
    @ApiModelProperty(value = "")
    public String getReminderFreq() {
        return reminderFreq;
    }

    public void setReminderFreq(String reminderFreq) {
        this.reminderFreq = reminderFreq;
    }

    public UserInput newsletters(Boolean newsletters) {
        this.newsletters = newsletters;
        return this;
    }

    /**
     * Get newsletters
     *
     * @return newsletters
     **/
    @ApiModelProperty(value = "")
    public Boolean isNewsletters() {
        return newsletters;
    }

    public void setNewsletters(Boolean newsletters) {
        this.newsletters = newsletters;
    }

    public UserInput churchId(Long churchId) {
        this.churchId = churchId;
        return this;
    }

    /**
     * Get churchId
     *
     * @return churchId
     **/
    @ApiModelProperty(value = "")
    public Long getChurchId() {
        return churchId;
    }

    public void setChurchId(Long churchId) {
        this.churchId = churchId;
    }

    public UserInput countryId(Long countryId) {
        this.countryId = countryId;
        return this;
    }

    /**
     * Get countryId
     *
     * @return countryId
     **/
    @ApiModelProperty(value = "")
    public Long getCountryId() {
        return countryId;
    }

    public void setCountryId(Long countryId) {
        this.countryId = countryId;
    }

    public UserInput language(String language) {
        this.language = language;
        return this;
    }

    /**
     * Get language
     *
     * @return language
     **/
    @ApiModelProperty(value = "")
    public String getLanguage() {
        return language;
    }

    public void setLanguage(String language) {
        this.language = language;
    }

    public UserInput timeAllocation(Long timeAllocation) {
        this.timeAllocation = timeAllocation;
        return this;
    }

    /**
     * Get timeAllocation
     *
     * @return timeAllocation
     **/
    @ApiModelProperty(value = "")
    public Long getTimeAllocation() {
        return timeAllocation;
    }

    public void setTimeAllocation(Long timeAllocation) {
        this.timeAllocation = timeAllocation;
    }

    public UserInput memorized(Long memorized) {
        this.memorized = memorized;
        return this;
    }

    /**
     * Get memorized
     *
     * @return memorized
     **/
    @ApiModelProperty(value = "")
    public Long getMemorized() {
        return memorized;
    }

    public void setMemorized(Long memorized) {
        this.memorized = memorized;
    }

    public UserInput learning(Long learning) {
        this.learning = learning;
        return this;
    }

    /**
     * Get learning
     *
     * @return learning
     **/
    @ApiModelProperty(value = "")
    public Long getLearning() {
        return learning;
    }

    public void setLearning(Long learning) {
        this.learning = learning;
    }

    public UserInput lastActivityDate(LocalDate lastActivityDate) {
        this.lastActivityDate = lastActivityDate;
        return this;
    }

    /**
     * Get lastActivityDate
     *
     * @return lastActivityDate
     **/
    @ApiModelProperty(value = "")
    public LocalDate getLastActivityDate() {
        return lastActivityDate;
    }

    public void setLastActivityDate(LocalDate lastActivityDate) {
        this.lastActivityDate = lastActivityDate;
    }

    public UserInput showEcho(Boolean showEcho) {
        this.showEcho = showEcho;
        return this;
    }

    /**
     * Get showEcho
     *
     * @return showEcho
     **/
    @ApiModelProperty(value = "")
    public Boolean isShowEcho() {
        return showEcho;
    }

    public void setShowEcho(Boolean showEcho) {
        this.showEcho = showEcho;
    }

    public UserInput maxInterval(Long maxInterval) {
        this.maxInterval = maxInterval;
        return this;
    }

    /**
     * Get maxInterval
     *
     * @return maxInterval
     **/
    @ApiModelProperty(value = "")
    public Long getMaxInterval() {
        return maxInterval;
    }

    public void setMaxInterval(Long maxInterval) {
        this.maxInterval = maxInterval;
    }

    public UserInput mnemonicUse(LocalDate mnemonicUse) {
        this.mnemonicUse = mnemonicUse;
        return this;
    }

    /**
     * Get mnemonicUse
     *
     * @return mnemonicUse
     **/
    @ApiModelProperty(value = "")
    public LocalDate getMnemonicUse() {
        return mnemonicUse;
    }

    public void setMnemonicUse(LocalDate mnemonicUse) {
        this.mnemonicUse = mnemonicUse;
    }

    public UserInput americanStateId(Long americanStateId) {
        this.americanStateId = americanStateId;
        return this;
    }

    /**
     * Get americanStateId
     *
     * @return americanStateId
     **/
    @ApiModelProperty(value = "")
    public Long getAmericanStateId() {
        return americanStateId;
    }

    public void setAmericanStateId(Long americanStateId) {
        this.americanStateId = americanStateId;
    }

    public UserInput accuracy(Long accuracy) {
        this.accuracy = accuracy;
        return this;
    }

    /**
     * Get accuracy
     *
     * @return accuracy
     **/
    @ApiModelProperty(value = "")
    public Long getAccuracy() {
        return accuracy;
    }

    public void setAccuracy(Long accuracy) {
        this.accuracy = accuracy;
    }

    public UserInput allRefs(Boolean allRefs) {
        this.allRefs = allRefs;
        return this;
    }

    /**
     * Get allRefs
     *
     * @return allRefs
     **/
    @ApiModelProperty(value = "")
    public Boolean isAllRefs() {
        return allRefs;
    }

    public void setAllRefs(Boolean allRefs) {
        this.allRefs = allRefs;
    }

    public UserInput rank(Long rank) {
        this.rank = rank;
        return this;
    }

    /**
     * Get rank
     *
     * @return rank
     **/
    @ApiModelProperty(value = "")
    public Long getRank() {
        return rank;
    }

    public void setRank(Long rank) {
        this.rank = rank;
    }

    public UserInput refGrade(Long refGrade) {
        this.refGrade = refGrade;
        return this;
    }

    /**
     * Get refGrade
     *
     * @return refGrade
     **/
    @ApiModelProperty(value = "")
    public Long getRefGrade() {
        return refGrade;
    }

    public void setRefGrade(Long refGrade) {
        this.refGrade = refGrade;
    }

    public UserInput gender(String gender) {
        this.gender = gender;
        return this;
    }

    /**
     * Get gender
     *
     * @return gender
     **/
    @ApiModelProperty(value = "")
    public String getGender() {
        return gender;
    }

    public void setGender(String gender) {
        this.gender = gender;
    }

    public UserInput translation(String translation) {
        this.translation = translation;
        return this;
    }

    /**
     * Get translation
     *
     * @return translation
     **/
    @ApiModelProperty(value = "")
    public String getTranslation() {
        return translation;
    }

    public void setTranslation(String translation) {
        this.translation = translation;
    }

    public UserInput level(Long level) {
        this.level = level;
        return this;
    }

    /**
     * Get level
     *
     * @return level
     **/
    @ApiModelProperty(value = "")
    public Long getLevel() {
        return level;
    }

    public void setLevel(Long level) {
        this.level = level;
    }

    public UserInput referredBy(Long referredBy) {
        this.referredBy = referredBy;
        return this;
    }

    /**
     * Get referredBy
     *
     * @return referredBy
     **/
    @ApiModelProperty(value = "")
    public Long getReferredBy() {
        return referredBy;
    }

    public void setReferredBy(Long referredBy) {
        this.referredBy = referredBy;
    }

    public UserInput showEmail(Boolean showEmail) {
        this.showEmail = showEmail;
        return this;
    }

    /**
     * Get showEmail
     *
     * @return showEmail
     **/
    @ApiModelProperty(value = "")
    public Boolean isShowEmail() {
        return showEmail;
    }

    public void setShowEmail(Boolean showEmail) {
        this.showEmail = showEmail;
    }

    public UserInput autoWorkLoad(Boolean autoWorkLoad) {
        this.autoWorkLoad = autoWorkLoad;
        return this;
    }

    /**
     * Get autoWorkLoad
     *
     * @return autoWorkLoad
     **/
    @ApiModelProperty(value = "")
    public Boolean isAutoWorkLoad() {
        return autoWorkLoad;
    }

    public void setAutoWorkLoad(Boolean autoWorkLoad) {
        this.autoWorkLoad = autoWorkLoad;
    }

    public UserInput admin(Boolean admin) {
        this.admin = admin;
        return this;
    }

    /**
     * Get admin
     *
     * @return admin
     **/
    @ApiModelProperty(value = "")
    public Boolean isAdmin() {
        return admin;
    }

    public void setAdmin(Boolean admin) {
        this.admin = admin;
    }

    public UserInput groupId(Long groupId) {
        this.groupId = groupId;
        return this;
    }

    /**
     * Get groupId
     *
     * @return groupId
     **/
    @ApiModelProperty(value = "")
    public Long getGroupId() {
        return groupId;
    }

    public void setGroupId(Long groupId) {
        this.groupId = groupId;
    }

    public UserInput provider(String provider) {
        this.provider = provider;
        return this;
    }

    /**
     * Get provider
     *
     * @return provider
     **/
    @ApiModelProperty(value = "")
    public String getProvider() {
        return provider;
    }

    public void setProvider(String provider) {
        this.provider = provider;
    }

    public UserInput uid(String uid) {
        this.uid = uid;
        return this;
    }

    /**
     * Get uid
     *
     * @return uid
     **/
    @ApiModelProperty(value = "")
    public String getUid() {
        return uid;
    }

    public void setUid(String uid) {
        this.uid = uid;
    }

    public UserInput syncSubsections(Boolean syncSubsections) {
        this.syncSubsections = syncSubsections;
        return this;
    }

    /**
     * Get syncSubsections
     *
     * @return syncSubsections
     **/
    @ApiModelProperty(value = "")
    public Boolean isSyncSubsections() {
        return syncSubsections;
    }

    public void setSyncSubsections(Boolean syncSubsections) {
        this.syncSubsections = syncSubsections;
    }

    public UserInput quizAlert(Boolean quizAlert) {
        this.quizAlert = quizAlert;
        return this;
    }

    /**
     * Get quizAlert
     *
     * @return quizAlert
     **/
    @ApiModelProperty(value = "")
    public Boolean isQuizAlert() {
        return quizAlert;
    }

    public void setQuizAlert(Boolean quizAlert) {
        this.quizAlert = quizAlert;
    }

    public UserInput deviceToken(String deviceToken) {
        this.deviceToken = deviceToken;
        return this;
    }

    /**
     * iOS device token
     *
     * @return deviceToken
     **/
    @ApiModelProperty(value = "iOS device token")
    public String getDeviceToken() {
        return deviceToken;
    }

    public void setDeviceToken(String deviceToken) {
        this.deviceToken = deviceToken;
    }

    public UserInput deviceType(String deviceType) {
        this.deviceType = deviceType;
        return this;
    }

    /**
     * Options: iOS, android, windows
     *
     * @return deviceType
     **/
    @ApiModelProperty(value = "Options: iOS, android, windows")
    public String getDeviceType() {
        return deviceType;
    }

    public void setDeviceType(String deviceType) {
        this.deviceType = deviceType;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        UserInput userInput = (UserInput) o;
        return Objects.equals(this.id, userInput.id) &&
                Objects.equals(this.login, userInput.login) &&
                Objects.equals(this.identityUrl, userInput.identityUrl) &&
                Objects.equals(this.name, userInput.name) &&
                Objects.equals(this.email, userInput.email) &&
                Objects.equals(this.rememberTokenExpiresAt, userInput.rememberTokenExpiresAt) &&
                Objects.equals(this.deletedAt, userInput.deletedAt) &&
                Objects.equals(this.createdAt, userInput.createdAt) &&
                Objects.equals(this.updatedAt, userInput.updatedAt) &&
                Objects.equals(this.lastReminder, userInput.lastReminder) &&
                Objects.equals(this.reminderFreq, userInput.reminderFreq) &&
                Objects.equals(this.newsletters, userInput.newsletters) &&
                Objects.equals(this.churchId, userInput.churchId) &&
                Objects.equals(this.countryId, userInput.countryId) &&
                Objects.equals(this.language, userInput.language) &&
                Objects.equals(this.timeAllocation, userInput.timeAllocation) &&
                Objects.equals(this.memorized, userInput.memorized) &&
                Objects.equals(this.learning, userInput.learning) &&
                Objects.equals(this.lastActivityDate, userInput.lastActivityDate) &&
                Objects.equals(this.showEcho, userInput.showEcho) &&
                Objects.equals(this.maxInterval, userInput.maxInterval) &&
                Objects.equals(this.mnemonicUse, userInput.mnemonicUse) &&
                Objects.equals(this.americanStateId, userInput.americanStateId) &&
                Objects.equals(this.accuracy, userInput.accuracy) &&
                Objects.equals(this.allRefs, userInput.allRefs) &&
                Objects.equals(this.rank, userInput.rank) &&
                Objects.equals(this.refGrade, userInput.refGrade) &&
                Objects.equals(this.gender, userInput.gender) &&
                Objects.equals(this.translation, userInput.translation) &&
                Objects.equals(this.level, userInput.level) &&
                Objects.equals(this.referredBy, userInput.referredBy) &&
                Objects.equals(this.showEmail, userInput.showEmail) &&
                Objects.equals(this.autoWorkLoad, userInput.autoWorkLoad) &&
                Objects.equals(this.admin, userInput.admin) &&
                Objects.equals(this.groupId, userInput.groupId) &&
                Objects.equals(this.provider, userInput.provider) &&
                Objects.equals(this.uid, userInput.uid) &&
                Objects.equals(this.syncSubsections, userInput.syncSubsections) &&
                Objects.equals(this.quizAlert, userInput.quizAlert) &&
                Objects.equals(this.deviceToken, userInput.deviceToken) &&
                Objects.equals(this.deviceType, userInput.deviceType);
    }

    @Override
    public int hashCode() {
        return Objects.hash(id, login, identityUrl, name, email, rememberTokenExpiresAt, deletedAt, createdAt, updatedAt, lastReminder, reminderFreq, newsletters, churchId, countryId, language, timeAllocation, memorized, learning, lastActivityDate, showEcho, maxInterval, mnemonicUse, americanStateId, accuracy, allRefs, rank, refGrade, gender, translation, level, referredBy, showEmail, autoWorkLoad, admin, groupId, provider, uid, syncSubsections, quizAlert, deviceToken, deviceType);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class UserInput {\n");

        sb.append("    id: ").append(toIndentedString(id)).append("\n");
        sb.append("    login: ").append(toIndentedString(login)).append("\n");
        sb.append("    identityUrl: ").append(toIndentedString(identityUrl)).append("\n");
        sb.append("    name: ").append(toIndentedString(name)).append("\n");
        sb.append("    email: ").append(toIndentedString(email)).append("\n");
        sb.append("    rememberTokenExpiresAt: ").append(toIndentedString(rememberTokenExpiresAt)).append("\n");
        sb.append("    deletedAt: ").append(toIndentedString(deletedAt)).append("\n");
        sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
        sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
        sb.append("    lastReminder: ").append(toIndentedString(lastReminder)).append("\n");
        sb.append("    reminderFreq: ").append(toIndentedString(reminderFreq)).append("\n");
        sb.append("    newsletters: ").append(toIndentedString(newsletters)).append("\n");
        sb.append("    churchId: ").append(toIndentedString(churchId)).append("\n");
        sb.append("    countryId: ").append(toIndentedString(countryId)).append("\n");
        sb.append("    language: ").append(toIndentedString(language)).append("\n");
        sb.append("    timeAllocation: ").append(toIndentedString(timeAllocation)).append("\n");
        sb.append("    memorized: ").append(toIndentedString(memorized)).append("\n");
        sb.append("    learning: ").append(toIndentedString(learning)).append("\n");
        sb.append("    lastActivityDate: ").append(toIndentedString(lastActivityDate)).append("\n");
        sb.append("    showEcho: ").append(toIndentedString(showEcho)).append("\n");
        sb.append("    maxInterval: ").append(toIndentedString(maxInterval)).append("\n");
        sb.append("    mnemonicUse: ").append(toIndentedString(mnemonicUse)).append("\n");
        sb.append("    americanStateId: ").append(toIndentedString(americanStateId)).append("\n");
        sb.append("    accuracy: ").append(toIndentedString(accuracy)).append("\n");
        sb.append("    allRefs: ").append(toIndentedString(allRefs)).append("\n");
        sb.append("    rank: ").append(toIndentedString(rank)).append("\n");
        sb.append("    refGrade: ").append(toIndentedString(refGrade)).append("\n");
        sb.append("    gender: ").append(toIndentedString(gender)).append("\n");
        sb.append("    translation: ").append(toIndentedString(translation)).append("\n");
        sb.append("    level: ").append(toIndentedString(level)).append("\n");
        sb.append("    referredBy: ").append(toIndentedString(referredBy)).append("\n");
        sb.append("    showEmail: ").append(toIndentedString(showEmail)).append("\n");
        sb.append("    autoWorkLoad: ").append(toIndentedString(autoWorkLoad)).append("\n");
        sb.append("    admin: ").append(toIndentedString(admin)).append("\n");
        sb.append("    groupId: ").append(toIndentedString(groupId)).append("\n");
        sb.append("    provider: ").append(toIndentedString(provider)).append("\n");
        sb.append("    uid: ").append(toIndentedString(uid)).append("\n");
        sb.append("    syncSubsections: ").append(toIndentedString(syncSubsections)).append("\n");
        sb.append("    quizAlert: ").append(toIndentedString(quizAlert)).append("\n");
        sb.append("    deviceToken: ").append(toIndentedString(deviceToken)).append("\n");
        sb.append("    deviceType: ").append(toIndentedString(deviceType)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

