/*
 * Swagger Memverse
 * Memverse API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.memverse.apiclient.api;

import com.memverse.apiclient.ApiException;
import com.memverse.apiclient.model.User;

import org.junit.Ignore;
import org.junit.Test;

/**
 * API tests for AuthorizationApi
 */
@Ignore
public class AuthorizationApiTest {

    private final AuthorizationApi api = new AuthorizationApi();


    /**
     * Request an API access token. This access token should be used for all future requests as per the Oauth2 Password Flow.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void requestAccessTokenTest() throws ApiException {
        String grantType = null;
        String username = null;
        String password = null;
        String clientId = null;
        User response = api.requestAccessToken(grantType, username, password, clientId);

        // TODO: test validations
    }

}
