/*
 * Swagger Memverse
 * Memverse API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.memverse.apiclient.api;

import com.memverse.apiclient.ApiException;
import com.memverse.apiclient.model.User;

import org.junit.Before;
import org.junit.Test;

import static com.memverse.apiclient.CustomMatchers.isNotNullOrEmptyString;
import static org.junit.Assert.assertNotNull;
import static org.junit.Assert.assertThat;

/**
 * API tests for CurrentUserApi
 */
public class CurrentUserApiTest extends BaseApiTest {

    private final CurrentUserApi api = new CurrentUserApi();

    @Before
    public void setup() throws ApiException {
        configureAuthentication(api);
    }

    /**
     * Returns credential for current user
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void findCurrentUserTest() throws ApiException {
        User response = api.findCurrentUser();

        assertNotNull(response);
        assertNotNull(response.getId());
        assertThat(response.getLogin(), isNotNullOrEmptyString());
        // assertThat(response.getIdentityUrl(), isNotNullOrEmptyString());
        assertThat(response.getName(), isNotNullOrEmptyString());
        assertThat(response.getEmail(), isNotNullOrEmptyString());
        // assertThat(response.getRememberTokenExpiresAt(), isNotNullOrEmptyString());
        // assertThat(response.getDeletedAt(), isNotNullOrEmptyString());
        assertThat(response.getCreatedAt(), isNotNullOrEmptyString());
        assertThat(response.getUpdatedAt(), isNotNullOrEmptyString());
        assertNotNull(response.getLastReminder());
        assertThat(response.getReminderFreq(), isNotNullOrEmptyString());
        assertNotNull(response.isNewsletters());
        // assertNotNull(response.getChurchId());
        // assertNotNull(response.getCountryId());
        assertThat(response.getLanguage(), isNotNullOrEmptyString());
        assertNotNull(response.getTimeAllocation());
        assertNotNull(response.getMemorized());
        assertNotNull(response.getLearning());
        // ...
    }

}
