/*
 * Swagger Memverse
 * Memverse API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.memverse.apiclient.api;

import com.memverse.apiclient.ApiException;
import com.memverse.apiclient.model.Memverse;
import com.memverse.apiclient.model.MemverseInput;

import org.junit.Ignore;
import org.junit.Test;

/**
 * API tests for MemverseApi
 */
@Ignore
public class MemverseApiTest {

    private final MemverseApi api = new MemverseApi();


    /**
     * Creates a new memory verse
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void createMemverseTest() throws ApiException {
        MemverseInput verseId = null;
        Memverse response = api.createMemverse(verseId);

        // TODO: test validations
    }

    /**
     * Delete a memory verse
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void deleteMemverseByIdTest() throws ApiException {
        Long id = null;
        Memverse response = api.deleteMemverseById(id);

        // TODO: test validations
    }

    /**
     * Returns a single memory verse
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void findMemverseByIdTest() throws ApiException {
        Long id = null;
        Memverse response = api.findMemverseById(id);

        // TODO: test validations
    }

    /**
     * Returns memory verses for current user
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void showMemversesTest() throws ApiException {
        String sort = null;
        Long page = null;
        Memverse response = api.showMemverses(sort, page);

        // TODO: test validations
    }

    /**
     * Returns memory verses for a given passage
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void showMemversesForPassageTest() throws ApiException {
        Long passageId = null;
        Long page = null;
        Memverse response = api.showMemversesForPassage(passageId, page);

        // TODO: test validations
    }

    /**
     * Record a rating for a memory verse
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void updateMemverseByIdTest() throws ApiException {
        Long id = null;
        Long q = null;
        Memverse response = api.updateMemverseById(id, q);

        // TODO: test validations
    }

}
