/*
 * Swagger Memverse
 * Memverse API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.memverse.apiclient.api;

import com.memverse.apiclient.ApiException;
import com.memverse.apiclient.model.ProgressReport;

import org.junit.Before;
import org.junit.Ignore;
import org.junit.Test;

/**
 * API tests for ProgressReportsApi
 */
@Ignore
public class ProgressReportsApiTest extends BaseApiTest {

    private final ProgressReportsApi api = new ProgressReportsApi();

    @Before
    public void setup() throws ApiException {
        configureAuthentication(api);
    }

    /**
     * Returns progress data for user
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void showUserProgressTest() throws ApiException {
        ProgressReport response = api.showUserProgress();

        // TODO: test validations
    }

}
