/*
 * Swagger Memverse
 * Memverse API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.memverse.apiclient.api;

import com.memverse.apiclient.ApiException;
import com.memverse.apiclient.model.Quiz;

import org.junit.Before;
import org.junit.Ignore;
import org.junit.Test;

/**
 * API tests for QuizApi
 */
@Ignore
public class QuizApiTest extends BaseApiTest {

    private final QuizApi api = new QuizApi();

    @Before
    public void setup() throws ApiException {
        configureAuthentication(api);
    }

    /**
     * Returns the upcoming live quiz
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void findUpcomingQuizTest() throws ApiException {
        Quiz response = api.findUpcomingQuiz();

        // TODO: test validations
    }

    /**
     * Record a user score for a live quiz question
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void recordUserScoreTest() throws ApiException {
        String usrId = null;
        String usrName = null;
        String usrLogin = null;
        Long questionId = null;
        Long questionNum = null;
        Long score = null;
        api.recordUserScore(usrId, usrName, usrLogin, questionId, questionNum, score);

        // TODO: test validations
    }

}
