/*
 * Swagger Memverse
 * Memverse API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.memverse.apiclient.api;

import com.memverse.apiclient.ApiException;
import com.memverse.apiclient.model.User;

import org.junit.Before;
import org.junit.Ignore;
import org.junit.Test;

/**
 * API tests for UserApi
 */
@Ignore
public class UserApiTest extends BaseApiTest {

    private final UserApi api = new UserApi();

    @Before
    public void setup() throws ApiException {
        configureAuthentication(api);
    }

    /**
     * Creates a new user
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void createUserTest() throws ApiException {
        String name = null;
        String email = null;
        String password = null;
        User response = api.createUser(name, email, password);

        // TODO: test validations
    }

    /**
     * Returns a single user
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void findUserByIdTest() throws ApiException {
        Long id = null;
        User response = api.findUserById(id);

        // TODO: test validations
    }

    /**
     * Partial updates to a user
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void updateUserByIdTest() throws ApiException {
        Long id = null;
        User response = api.updateUserById(id);

        // TODO: test validations
    }

}
