/*
 * Swagger Memverse
 * Memverse API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.memverse.apiclient.api;

import com.memverse.apiclient.ApiException;
import com.memverse.apiclient.model.Verse;

import org.junit.Ignore;
import org.junit.Test;

/**
 * API tests for VerseApi
 */
@Ignore
public class VerseApiTest {

    private final VerseApi api = new VerseApi();


    /**
     * Lookup a chapter by translation, book, and chapter number
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void findChapterTest() throws ApiException {
        String tl = null;
        String bk = null;
        String ch = null;
        Verse response = api.findChapter(tl, bk, ch);

        // TODO: test validations
    }

    /**
     * Returns a single verse
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void findVerseByIdTest() throws ApiException {
        Long id = null;
        Verse response = api.findVerseById(id);

        // TODO: test validations
    }

    /**
     * Search for a verse
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void findVerseBySearchTermTest() throws ApiException {
        String searchParams = null;
        Verse response = api.findVerseBySearchTerm(searchParams);

        // TODO: test validations
    }

    /**
     * Lookup a verse by translation, book, chapter, and verse number
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void findVerseByTlBkChVsTest() throws ApiException {
        String tl = null;
        String bk = null;
        String ch = null;
        String vs = null;
        Verse response = api.findVerseByTlBkChVs(tl, bk, ch, vs);

        // TODO: test validations
    }

}
