/*
 * Swagger Memverse
 * Memverse API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.memverse.android.apiclient.model;

import com.google.gson.annotations.SerializedName;

import java.util.Objects;

import io.swagger.annotations.ApiModelProperty;

/**
 * Passage
 * Generated by `java -jar swagger-codegen-cli.jar generate --lang java --library retrofit2 --input-spec swagger_spec.json`
 * Created on 2017-12-30T15:34:14.889+13:00
 */
public class Passage {
    @SerializedName("id")
    private Long id = null;

    @SerializedName("user_id")
    private Long userId = null;

    @SerializedName("ref")
    private String ref = null;

    @SerializedName("book")
    private String book = null;

    @SerializedName("book_index")
    private Long bookIndex = null;

    @SerializedName("chapter")
    private String chapter = null;

    @SerializedName("first_verse")
    private Long firstVerse = null;

    @SerializedName("last_verse")
    private Long lastVerse = null;

    public Passage id(Long id) {
        this.id = id;
        return this;
    }

    /**
     * Get id
     *
     * @return id
     **/
    @ApiModelProperty(required = true, value = "")
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Passage userId(Long userId) {
        this.userId = userId;
        return this;
    }

    /**
     * Get userId
     *
     * @return userId
     **/
    @ApiModelProperty(value = "")
    public Long getUserId() {
        return userId;
    }

    public void setUserId(Long userId) {
        this.userId = userId;
    }

    public Passage ref(String ref) {
        this.ref = ref;
        return this;
    }

    /**
     * Get ref
     *
     * @return ref
     **/
    @ApiModelProperty(required = true, value = "")
    public String getRef() {
        return ref;
    }

    public void setRef(String ref) {
        this.ref = ref;
    }

    public Passage book(String book) {
        this.book = book;
        return this;
    }

    /**
     * Get book
     *
     * @return book
     **/
    @ApiModelProperty(required = true, value = "")
    public String getBook() {
        return book;
    }

    public void setBook(String book) {
        this.book = book;
    }

    public Passage bookIndex(Long bookIndex) {
        this.bookIndex = bookIndex;
        return this;
    }

    /**
     * Get bookIndex
     *
     * @return bookIndex
     **/
    @ApiModelProperty(value = "")
    public Long getBookIndex() {
        return bookIndex;
    }

    public void setBookIndex(Long bookIndex) {
        this.bookIndex = bookIndex;
    }

    public Passage chapter(String chapter) {
        this.chapter = chapter;
        return this;
    }

    /**
     * Get chapter
     *
     * @return chapter
     **/
    @ApiModelProperty(required = true, value = "")
    public String getChapter() {
        return chapter;
    }

    public void setChapter(String chapter) {
        this.chapter = chapter;
    }

    public Passage firstVerse(Long firstVerse) {
        this.firstVerse = firstVerse;
        return this;
    }

    /**
     * Get firstVerse
     *
     * @return firstVerse
     **/
    @ApiModelProperty(required = true, value = "")
    public Long getFirstVerse() {
        return firstVerse;
    }

    public void setFirstVerse(Long firstVerse) {
        this.firstVerse = firstVerse;
    }

    public Passage lastVerse(Long lastVerse) {
        this.lastVerse = lastVerse;
        return this;
    }

    /**
     * Get lastVerse
     *
     * @return lastVerse
     **/
    @ApiModelProperty(required = true, value = "")
    public Long getLastVerse() {
        return lastVerse;
    }

    public void setLastVerse(Long lastVerse) {
        this.lastVerse = lastVerse;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        Passage passage = (Passage) o;
        return Objects.equals(this.id, passage.id) &&
                Objects.equals(this.userId, passage.userId) &&
                Objects.equals(this.ref, passage.ref) &&
                Objects.equals(this.book, passage.book) &&
                Objects.equals(this.bookIndex, passage.bookIndex) &&
                Objects.equals(this.chapter, passage.chapter) &&
                Objects.equals(this.firstVerse, passage.firstVerse) &&
                Objects.equals(this.lastVerse, passage.lastVerse);
    }

    @Override
    public int hashCode() {
        return Objects.hash(id, userId, ref, book, bookIndex, chapter, firstVerse, lastVerse);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class Passage {\n");

        sb.append("    id: ").append(toIndentedString(id)).append("\n");
        sb.append("    userId: ").append(toIndentedString(userId)).append("\n");
        sb.append("    ref: ").append(toIndentedString(ref)).append("\n");
        sb.append("    book: ").append(toIndentedString(book)).append("\n");
        sb.append("    bookIndex: ").append(toIndentedString(bookIndex)).append("\n");
        sb.append("    chapter: ").append(toIndentedString(chapter)).append("\n");
        sb.append("    firstVerse: ").append(toIndentedString(firstVerse)).append("\n");
        sb.append("    lastVerse: ").append(toIndentedString(lastVerse)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

