/*
 * Swagger Memverse
 * Memverse API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.memverse.android.apiclient.model;

import com.google.gson.annotations.SerializedName;

import java.util.Objects;

import io.swagger.annotations.ApiModelProperty;

/**
 * Quiz
 * Generated by `java -jar swagger-codegen-cli.jar generate --lang java --library retrofit2 --input-spec swagger_spec.json`
 * Created on 2017-12-30T15:34:14.889+13:00
 */
public class Quiz {
    @SerializedName("id")
    private Long id = null;

    @SerializedName("name")
    private String name = null;

    @SerializedName("description")
    private String description = null;

    @SerializedName("quiz_questions_count")
    private Long quizQuestionsCount = null;

    @SerializedName("quiz_length")
    private Long quizLength = null;

    @SerializedName("start_time")
    private String startTime = null;

    public Quiz id(Long id) {
        this.id = id;
        return this;
    }

    /**
     * Get id
     *
     * @return id
     **/
    @ApiModelProperty(required = true, value = "")
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Quiz name(String name) {
        this.name = name;
        return this;
    }

    /**
     * Get name
     *
     * @return name
     **/
    @ApiModelProperty(required = true, value = "")
    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Quiz description(String description) {
        this.description = description;
        return this;
    }

    /**
     * Get description
     *
     * @return description
     **/
    @ApiModelProperty(required = true, value = "")
    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public Quiz quizQuestionsCount(Long quizQuestionsCount) {
        this.quizQuestionsCount = quizQuestionsCount;
        return this;
    }

    /**
     * Get quizQuestionsCount
     *
     * @return quizQuestionsCount
     **/
    @ApiModelProperty(required = true, value = "")
    public Long getQuizQuestionsCount() {
        return quizQuestionsCount;
    }

    public void setQuizQuestionsCount(Long quizQuestionsCount) {
        this.quizQuestionsCount = quizQuestionsCount;
    }

    public Quiz quizLength(Long quizLength) {
        this.quizLength = quizLength;
        return this;
    }

    /**
     * Get quizLength
     *
     * @return quizLength
     **/
    @ApiModelProperty(required = true, value = "")
    public Long getQuizLength() {
        return quizLength;
    }

    public void setQuizLength(Long quizLength) {
        this.quizLength = quizLength;
    }

    public Quiz startTime(String startTime) {
        this.startTime = startTime;
        return this;
    }

    /**
     * Get startTime
     *
     * @return startTime
     **/
    @ApiModelProperty(required = true, value = "")
    public String getStartTime() {
        return startTime;
    }

    public void setStartTime(String startTime) {
        this.startTime = startTime;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        Quiz quiz = (Quiz) o;
        return Objects.equals(this.id, quiz.id) &&
                Objects.equals(this.name, quiz.name) &&
                Objects.equals(this.description, quiz.description) &&
                Objects.equals(this.quizQuestionsCount, quiz.quizQuestionsCount) &&
                Objects.equals(this.quizLength, quiz.quizLength) &&
                Objects.equals(this.startTime, quiz.startTime);
    }

    @Override
    public int hashCode() {
        return Objects.hash(id, name, description, quizQuestionsCount, quizLength, startTime);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class Quiz {\n");

        sb.append("    id: ").append(toIndentedString(id)).append("\n");
        sb.append("    name: ").append(toIndentedString(name)).append("\n");
        sb.append("    description: ").append(toIndentedString(description)).append("\n");
        sb.append("    quizQuestionsCount: ").append(toIndentedString(quizQuestionsCount)).append("\n");
        sb.append("    quizLength: ").append(toIndentedString(quizLength)).append("\n");
        sb.append("    startTime: ").append(toIndentedString(startTime)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

