/*
 * Swagger Memverse
 * Memverse API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.memverse.android.apiclient.model;

import com.google.gson.annotations.SerializedName;

import java.math.BigDecimal;
import java.util.Objects;

import io.swagger.annotations.ApiModelProperty;

/**
 * Verse
 * Generated by `java -jar swagger-codegen-cli.jar generate --lang java --library retrofit2 --input-spec swagger_spec.json`
 * Created on 2017-12-30T15:34:14.889+13:00
 */
public class Verse {
    @SerializedName("id")
    private Long id = null;

    @SerializedName("translation")
    private String translation = null;

    @SerializedName("book_index")
    private Long bookIndex = null;

    @SerializedName("book")
    private String book = null;

    @SerializedName("chapter")
    private String chapter = null;

    @SerializedName("versenum")
    private Long versenum = null;

    @SerializedName("text")
    private String text = null;

    @SerializedName("created_at")
    private String createdAt = null;

    @SerializedName("updated_at")
    private String updatedAt = null;

    @SerializedName("verified")
    private Boolean verified = null;

    @SerializedName("error_flag")
    private Boolean errorFlag = null;

    @SerializedName("uberverse_id")
    private Long uberverseId = null;

    @SerializedName("checked_by")
    private String checkedBy = null;

    @SerializedName("memverses_count")
    private Long memversesCount = null;

    @SerializedName("difficulty")
    private BigDecimal difficulty = null;

    @SerializedName("popularity")
    private BigDecimal popularity = null;

    public Verse id(Long id) {
        this.id = id;
        return this;
    }

    /**
     * Get id
     *
     * @return id
     **/
    @ApiModelProperty(value = "")
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Verse translation(String translation) {
        this.translation = translation;
        return this;
    }

    /**
     * Get translation
     *
     * @return translation
     **/
    @ApiModelProperty(required = true, value = "")
    public String getTranslation() {
        return translation;
    }

    public void setTranslation(String translation) {
        this.translation = translation;
    }

    public Verse bookIndex(Long bookIndex) {
        this.bookIndex = bookIndex;
        return this;
    }

    /**
     * Get bookIndex
     *
     * @return bookIndex
     **/
    @ApiModelProperty(required = true, value = "")
    public Long getBookIndex() {
        return bookIndex;
    }

    public void setBookIndex(Long bookIndex) {
        this.bookIndex = bookIndex;
    }

    public Verse book(String book) {
        this.book = book;
        return this;
    }

    /**
     * Get book
     *
     * @return book
     **/
    @ApiModelProperty(required = true, value = "")
    public String getBook() {
        return book;
    }

    public void setBook(String book) {
        this.book = book;
    }

    public Verse chapter(String chapter) {
        this.chapter = chapter;
        return this;
    }

    /**
     * Get chapter
     *
     * @return chapter
     **/
    @ApiModelProperty(required = true, value = "")
    public String getChapter() {
        return chapter;
    }

    public void setChapter(String chapter) {
        this.chapter = chapter;
    }

    public Verse versenum(Long versenum) {
        this.versenum = versenum;
        return this;
    }

    /**
     * Get versenum
     *
     * @return versenum
     **/
    @ApiModelProperty(required = true, value = "")
    public Long getVersenum() {
        return versenum;
    }

    public void setVersenum(Long versenum) {
        this.versenum = versenum;
    }

    public Verse text(String text) {
        this.text = text;
        return this;
    }

    /**
     * Get text
     *
     * @return text
     **/
    @ApiModelProperty(value = "")
    public String getText() {
        return text;
    }

    public void setText(String text) {
        this.text = text;
    }

    public Verse createdAt(String createdAt) {
        this.createdAt = createdAt;
        return this;
    }

    /**
     * Get createdAt
     *
     * @return createdAt
     **/
    @ApiModelProperty(value = "")
    public String getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(String createdAt) {
        this.createdAt = createdAt;
    }

    public Verse updatedAt(String updatedAt) {
        this.updatedAt = updatedAt;
        return this;
    }

    /**
     * Get updatedAt
     *
     * @return updatedAt
     **/
    @ApiModelProperty(value = "")
    public String getUpdatedAt() {
        return updatedAt;
    }

    public void setUpdatedAt(String updatedAt) {
        this.updatedAt = updatedAt;
    }

    public Verse verified(Boolean verified) {
        this.verified = verified;
        return this;
    }

    /**
     * Get verified
     *
     * @return verified
     **/
    @ApiModelProperty(value = "")
    public Boolean isVerified() {
        return verified;
    }

    public void setVerified(Boolean verified) {
        this.verified = verified;
    }

    public Verse errorFlag(Boolean errorFlag) {
        this.errorFlag = errorFlag;
        return this;
    }

    /**
     * Get errorFlag
     *
     * @return errorFlag
     **/
    @ApiModelProperty(value = "")
    public Boolean isErrorFlag() {
        return errorFlag;
    }

    public void setErrorFlag(Boolean errorFlag) {
        this.errorFlag = errorFlag;
    }

    public Verse uberverseId(Long uberverseId) {
        this.uberverseId = uberverseId;
        return this;
    }

    /**
     * Get uberverseId
     *
     * @return uberverseId
     **/
    @ApiModelProperty(value = "")
    public Long getUberverseId() {
        return uberverseId;
    }

    public void setUberverseId(Long uberverseId) {
        this.uberverseId = uberverseId;
    }

    public Verse checkedBy(String checkedBy) {
        this.checkedBy = checkedBy;
        return this;
    }

    /**
     * Get checkedBy
     *
     * @return checkedBy
     **/
    @ApiModelProperty(value = "")
    public String getCheckedBy() {
        return checkedBy;
    }

    public void setCheckedBy(String checkedBy) {
        this.checkedBy = checkedBy;
    }

    public Verse memversesCount(Long memversesCount) {
        this.memversesCount = memversesCount;
        return this;
    }

    /**
     * Get memversesCount
     *
     * @return memversesCount
     **/
    @ApiModelProperty(value = "")
    public Long getMemversesCount() {
        return memversesCount;
    }

    public void setMemversesCount(Long memversesCount) {
        this.memversesCount = memversesCount;
    }

    public Verse difficulty(BigDecimal difficulty) {
        this.difficulty = difficulty;
        return this;
    }

    /**
     * Get difficulty
     *
     * @return difficulty
     **/
    @ApiModelProperty(value = "")
    public BigDecimal getDifficulty() {
        return difficulty;
    }

    public void setDifficulty(BigDecimal difficulty) {
        this.difficulty = difficulty;
    }

    public Verse popularity(BigDecimal popularity) {
        this.popularity = popularity;
        return this;
    }

    /**
     * Get popularity
     *
     * @return popularity
     **/
    @ApiModelProperty(value = "")
    public BigDecimal getPopularity() {
        return popularity;
    }

    public void setPopularity(BigDecimal popularity) {
        this.popularity = popularity;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        Verse verse = (Verse) o;
        return Objects.equals(this.id, verse.id) &&
                Objects.equals(this.translation, verse.translation) &&
                Objects.equals(this.bookIndex, verse.bookIndex) &&
                Objects.equals(this.book, verse.book) &&
                Objects.equals(this.chapter, verse.chapter) &&
                Objects.equals(this.versenum, verse.versenum) &&
                Objects.equals(this.text, verse.text) &&
                Objects.equals(this.createdAt, verse.createdAt) &&
                Objects.equals(this.updatedAt, verse.updatedAt) &&
                Objects.equals(this.verified, verse.verified) &&
                Objects.equals(this.errorFlag, verse.errorFlag) &&
                Objects.equals(this.uberverseId, verse.uberverseId) &&
                Objects.equals(this.checkedBy, verse.checkedBy) &&
                Objects.equals(this.memversesCount, verse.memversesCount) &&
                Objects.equals(this.difficulty, verse.difficulty) &&
                Objects.equals(this.popularity, verse.popularity);
    }

    @Override
    public int hashCode() {
        return Objects.hash(id, translation, bookIndex, book, chapter, versenum, text, createdAt, updatedAt, verified, errorFlag, uberverseId, checkedBy, memversesCount, difficulty, popularity);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class Verse {\n");

        sb.append("    id: ").append(toIndentedString(id)).append("\n");
        sb.append("    translation: ").append(toIndentedString(translation)).append("\n");
        sb.append("    bookIndex: ").append(toIndentedString(bookIndex)).append("\n");
        sb.append("    book: ").append(toIndentedString(book)).append("\n");
        sb.append("    chapter: ").append(toIndentedString(chapter)).append("\n");
        sb.append("    versenum: ").append(toIndentedString(versenum)).append("\n");
        sb.append("    text: ").append(toIndentedString(text)).append("\n");
        sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
        sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
        sb.append("    verified: ").append(toIndentedString(verified)).append("\n");
        sb.append("    errorFlag: ").append(toIndentedString(errorFlag)).append("\n");
        sb.append("    uberverseId: ").append(toIndentedString(uberverseId)).append("\n");
        sb.append("    checkedBy: ").append(toIndentedString(checkedBy)).append("\n");
        sb.append("    memversesCount: ").append(toIndentedString(memversesCount)).append("\n");
        sb.append("    difficulty: ").append(toIndentedString(difficulty)).append("\n");
        sb.append("    popularity: ").append(toIndentedString(popularity)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

