/*
 * Swagger Memverse
 * Memverse API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.memverse.apiclient.auth;

import com.google.gson.annotations.SerializedName;

public enum OAuthFlow {
    @SerializedName("accessCode")ACCESS_CODE,
    @SerializedName("implicit")IMPLICIT,
    @SerializedName("password")PASSWORD,
    @SerializedName("accessCode")APPLICATION
}
